#!/usr/bin/env python3
"""Generate docs/configuration.md from the code and the env template.

Hand-maintained settings tables drift. This one is derived from config.py's
actual defaults and .env.example's actual comments, so a default that changes in
code cannot silently keep its old value in the docs.

    python3 ops/gen-config-docs.py           # write docs/configuration.md
    python3 ops/gen-config-docs.py --check   # fail if it is stale (for CI)
"""
import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "processor"))

HEADER = """<!-- GENERATED by ops/gen-config-docs.py — do not edit by hand. -->
# Configuration

Every setting Atticus reads, with the default the code actually uses.

Settings live in `ops/.env` (pipeline settings, safe to read) and
`~/.config/ai/env` (credentials, never logged). That split is deliberate: one
private file owns every API key and consumers read it rather than keeping
copies.

"""


def parse_env_example() -> dict:
    """Map VAR -> the comment block immediately above it."""
    out, buf = {}, []
    for line in (REPO / "ops/.env.example").read_text().splitlines():
        st = line.strip()
        if st.startswith("#"):
            t = st.lstrip("#").strip()
            if t and not set(t) <= set("═─ "):
                buf.append(t)
        elif "=" in st and not st.startswith("#"):
            out[st.split("=", 1)[0].strip()] = " ".join(buf)
            buf = []
        elif not st:
            buf = []
    return out


def defaults_from_code() -> dict:
    """Pull the literal defaults out of Config.__init__ without executing it
    against a live environment (which would report *this host's* values)."""
    src = (REPO / "processor/config.py").read_text()
    out = {}
    for m in re.finditer(r'g\(\s*"([A-Z_]+)"\s*,\s*("(?:[^"\\]|\\.)*"|None)\s*\)', src):
        out[m.group(1)] = m.group(2).strip('"')
    for m in re.finditer(r'g\(\s*"([A-Z_]+)"\s*\)', src):
        out.setdefault(m.group(1), "")
    return out


def build() -> str:
    comments, defaults = parse_env_example(), defaults_from_code()
    rows = []
    for var in sorted(set(comments) | set(defaults)):
        if var.startswith("PLAUD_EMBEDDED"):
            continue
        d = defaults.get(var, "")
        shown = f"`{d}`" if d else "*(empty)*"
        why = comments.get(var, "").replace("|", "\\|")
        if len(why) > 200:
            why = why[:197] + "…"
        rows.append(f"| `{var}` | {shown} | {why} |")

    body = ("| Setting | Default | Purpose |\n|---|---|---|\n" + "\n".join(rows))
    return HEADER + body + f"\n\n*{len(rows)} settings.*\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    target = REPO / "docs/configuration.md"
    fresh = build()
    if args.check:
        current = target.read_text() if target.is_file() else ""
        if current != fresh:
            print("docs/configuration.md is stale — run ops/gen-config-docs.py",
                  file=sys.stderr)
            return 1
        print("configuration docs current")
        return 0
    target.write_text(fresh)
    print(f"wrote {target.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
